//User LOGIN
export const ADD_LOGIN = "ADD_LOGIN";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const REMOVE_LOGIN = "REMOVE_LOGIN";

//Vendor LOGIN
export const ADD_VENDOR_LOGIN = "ADD_VENDOR_LOGIN";
export const VENDOR_LOGIN_LOADING = "VENDOR_LOGIN_LOADING";
export const VENDOR_LOGIN_FAILED = "VENDOR_LOGIN_FAILED";
export const REMOVE_VENDOR_LOGIN = "REMOVE_VENDOR_LOGIN";

// VENDOR actionsTypes

export const VENDOR_GET_DATA = "VENDOR_GET_DATA";
export const VENDOR_SET_DATA = "VENDOR_SET_DATA";
export const VENDOR_FAIL_DATA = "VENDOR_FAIL_DATA";
export const DELETE_VENDOR_FAIL = "DELETE_VENDOR_FAIL";
export const POST_VENDOR_DATA = "POST_VENDOR_DATA";
export const POST_VENDOR_DATA_START = "POST_VENDOR_DATA_START";
export const POST_VENDOR_DATA_FAIL = "POST_VENDOR_DATA_FAIL";
export const EDIT_VENDOR_ROW_START = "EDIT_VENDOR_ROW_START";
export const EDIT_VENDOR_SET_DATA = "EDIT_VENDOR_SET_DATA";

export const FAIL_EDIT_VENDOR = "FAIL_EDIT_VENDOR";
export const CURRENT_USER_EDIT_VENDOR = "CURRENT_USER_EDIT_VENDOR";
export const UPDATE_VENDOR_DATA_START = "UPDATE_VENDOR_DATA_START";

// MyBooking actionsTypes

export const MYBOOKING_GET_DATA = "MYBOOKING_GET_DATA";
export const MYBOOKING_SET_DATA = "MYBOOKING_SET_DATA";
export const MYBOOKING_FAIL_DATA = "MYBOOKING_FAIL_DATA";
export const DELETE_MYBOOKING_FAIL = "DELETE_MYBOOKING_FAIL";
export const POST_MYBOOKING_DATA = "POST_MYBOOKING_DATA";
export const POST_MYBOOKING_DATA_START = "POST_MYBOOKING_DATA_START";
export const POST_MYBOOKING_DATA_FAIL = "POST_MYBOOKING_DATA_FAIL";
export const EDIT_MYBOOKING_ROW_START = "EDIT_MYBOOKING_ROW_START";

export const FAIL_EDIT_MYBOOKING = "FAIL_EDIT_MYBOOKING";
export const CURRENT_USER_EDIT_MYBOOKING = "CURRENT_USER_EDIT_MYBOOKING";
export const UPDATE_MYBOOKING_DATA_START = "UPDATE_MYBOOKING_DATA_START";

// Review actionsTypes

export const REVIEW_GET_DATA = "REVIEW_GET_DATA";
export const REVIEW_SET_DATA = "REVIEW_SET_DATA";
export const REVIEW_FAIL_DATA = "REVIEW_FAIL_DATA";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";
export const POST_REVIEW_DATA = "POST_REVIEW_DATA";
export const POST_REVIEW_DATA_START = "POST_REVIEW_DATA_START";
export const POST_REVIEW_DATA_FAIL = "POST_REVIEW_DATA_FAIL";
export const EDIT_REVIEW_ROW_START = "EDIT_REVIEW_ROW_START";

export const FAIL_EDIT_REVIEW = "FAIL_EDIT_REVIEW";
export const CURRENT_USER_EDIT_REVIEW = "CURRENT_USER_EDIT_REVIEW";
export const UPDATE_REVIEW_DATA_START = "UPDATE_REVIEW_DATA_START";

// VENDOR actionsTypes

export const VENDORTYPE_GET_DATA = "VENDORTYPE_GET_DATA";
export const VENDORTYPE_SET_DATA = "VENDORTYPE_SET_DATA";
export const VENDORTYPE_FAIL_DATA = "VENDORTYPE_FAIL_DATA";
export const DELETE_VENDORTYPE_FAIL = "DELETE_VENDORTYPE_FAIL";
export const POST_VENDORTYPE_DATA = "POST_VENDORTYPE_DATA";
export const POST_VENDORTYPE_DATA_START = "POST_VENDORTYPE_DATA_START";
export const POST_VENDORTYPE_DATA_FAIL = "POST_VENDORTYPE_DATA_FAIL";
export const EDIT_VENDORTYPE_ROW_START = "EDIT_VENDORTYPE_ROW_START";

export const FAIL_EDIT_VENDORTYPE = "FAIL_EDIT_VENDORTYPE";
export const CURRENT_USER_EDIT_VENDORTYPE = "CURRENT_USER_EDIT_VENDORTYPE";
export const UPDATE_VENDORTYPE_DATA_START = "UPDATE_VENDORTYPE_DATA_START";
